version: "3.9"

services:

  db:
    image: postgres
    volumes:
      - .:/code
    environment:
      - POSTGRES_DB=haclever_db
      - POSTGRES_USER=rainhunter_db
      - POSTGRES_PASSWORD=Rainhunter13?
    ports:
      - "5432:5432"

  web:
    build: .
    command: uvicorn main:app --host web --port 8000 --reload
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db